---
title: "田上 大嗣"
subtitle: "博士後期課程2年 / リサーチ・アシスタント@東京大学 | 非常勤研究員@Quemix Inc."
page-layout: article
toc: false
bibliography: references.bib
csl: publications.csl
link-citations: true
nocite: "@*"
filters:
  - presentation-list.lua
---

::: {#profile .profile}

所属
: [東京大学 大学院総合文化研究科](https://www.c.u-tokyo.ac.jp/) [広域科学専攻 相関基礎科学系](https://dbs.c.u-tokyo.ac.jp/)  
  [塩見雄毅研究室](https://yukishiomi.com/)  
  〒153-8902 東京都目黒区駒場4-6-1  
  東京大学16号館622号室

E-mail
: hirotsugu(at)g.ecc.u-tokyo.ac.jp

ORCID
: [0009-0000-7865-3173](https://orcid.org/0009-0000-7865-3173)

その他
: [Google Scholar](https://scholar.google.com/citations?user=hirotsugu-tagami) · [researchmap](https://researchmap.jp/hirotsugu-tagami) · [GitHub: hirotsugu-tagami](https://github.com/hirotsugu-tagami) 

:::

## 研究分野 {#research}

有機/無機単結晶の合成と低温物性測定を組み合わせ、磁性体におけるスピン輸送現象を研究しています。特に、反強磁性体や相変化材料における磁気構造の変化と電気伝導の関係に関心があります。

::: {.keywords}
- Organic/Inorganic Single Crystal Growth
- Magnetism
- Magnetoresitance
- Antiferromagnetic spintronics
- Spin transport
- Low-temperature physics
- Phase-change materials
- Kitaev materials
:::

## 発表 {#publications}

### **論文**
::: {#refs}
:::

### **発表リスト**

::: {#presentations-list}
:::

## 学歴 & 所属歴 {#education}

### **所属歴**
2026.05 — Present
: **Quemix Inc. 非常勤研究員**  
  インターンシップの延長として、非常勤研究員として勤務

2025.04 — Present
: **東京大学 リサーチ・アシスタント**  
  東京大学 大学院総合文化研究科 広域科学専攻 相関基礎科学系 塩見雄毅研究室

### **学歴**
2025.04 — Present
: **東京大学大学院 総合文化研究科**  
  博士後期課程

2023.04 — 2025.03
: **東京工業大学 物質理工学院**  
  応用化学系、修士（理学）

2019.04 — 2023.03
: **東京工業大学 物質理工学院**  
  応用化学系、学士（工学）

## 経歴 {#experience}

### **インターンシップ**
### [Quemix Inc.](https://www.quemix.com/)

**2026.4 — 2026.05 · リサーチ・インターンシップ**  
理論研究の中でも数値計算に従事していました。

### [OMRON SINIC X Corp.](https://www.omron.com/sinicx/)

**2022.10 — 2023.01 · リサーチ・インターンシップ**  
科学実験自動化のためのロボット実装に関わる研究をしました。  

### **主催**
### [第69回 物性若手夏の学校](https://cmpss.jp/ss2024/)

**2024.08 · 準備局（運営）**  
準備局集中ゼミC世話人として、東京大学の[森初果](https://hmori.issp.u-tokyo.ac.jp/index.html)先生と九州大学の[笠原裕一](https://sites.google.com/view/eqm-phys-kyushu-u/)先生を招待しました。

### **指導歴**
- 東京大学教養学部 統合自然科学科 学部3年授業「物質の姿」授業TA

<!-- ## アクセス {#access}

〒153-8902 
東京都目黒区駒場4-6-1  
東京大学駒場Iキャンパス16号館622号室  
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d359.079333711541!2d139.6834087527553!3d35.66125925434696!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x6018f3502e914393%3A0x515aef2e404b24ff!2z5pel5pys44CB44CSMTUzLTAwNDEg5p2x5Lqs6YO955uu6buS5Yy66aeS5aC077yT5LiB55uu77yYIDE25Y-36aSo!5e0!3m2!1sja!2sfr!4v1771234831742!5m2!1sja!2sfr" width="100%" height="450" style="border:0; width:100%; max-width:600px; aspect-ratio:4/3; height:auto;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe> -->
